<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="mrolap03" failures="1" tests="3" name="Default test(failed)" time="0.121" errors="0" timestamp="2024-10-17T14:37:56 IST">
  <testcase classname="Test.TestKeywords" name="test_B" time="0.022">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at Test.TestKeywords.test_B(TestKeywords.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 8 stack frames]]>
    </failure>
  </testcase> <!-- test_B -->
  <testcase classname="Test.TestKeywords" name="test_C" time="0.003"/>
  <testcase classname="Test.TestKeywords" name="test_A" time="0.0">
    <skipped/>
  </testcase> <!-- test_A -->
  <testcase classname="Test.TestKeywords" name="test_D" time="0.0">
    <ignored/>
  </testcase> <!-- test_D -->
</testsuite> <!-- Default test(failed) -->
